paths:
  base: /Users/nsofroniew/Documents/data/multiomics/enformer
  adata: /Users/nsofroniew/Documents/data/multiomics/cell_census/tabula_sapiens_by_features_with_embeds_new_norm.h5ad
  chkpt: null
adata:
  expression_layer: null
  var_embedding: embedding
  obs_embedding: null
model:
  head: Linear
params:
  batch_size: 1024
