defaults:
  - data_module: masked_var
  - preprocessing: standard
  - module/optimizer: adamw
  - module/model: transformer
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} # /home/ec2-user/ or /Users/nsofroniew/Documents/data/rosa/

paths:
  base: /home/ec2-user/cell_census # /home/ec2-user/ or /Users/nsofroniew/Documents/data/multiomics/
  dataset: tabula_sapiens
  preprocessed: _sample_${preprocessing.bulk_data.sample_col}__label_${preprocessing.bulk_data.label_col} # 5x_top10_pc ... gene_prot
  chkpt: /home/ec2-user/outputs/2023-05-19/16-44-49/checkpoints/last.ckpt # null

module:
  criterion:
    loss_function: ce

