hydra:
  run:
      dir: /home/ec2-user/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} # /home/ec2-user/ or /Users/nsofroniew/Documents/data/rosa/
paths:
  base: /home/ec2-user/cell_census # /home/ec2-user/ or /Users/nsofroniew/Documents/data/multiomics/
  dataset: tabula_sapiens
  preprocessed: _sample_${preprocessing.bulk_data.sample_col}__label_${preprocessing.bulk_data.label_col}
  chkpt: null
preprocessing:
  gene_embeddings:
    path: /Users/nsofroniew/Documents/data/multiomics/enformer/Homo_sapiens.GRCh38.genes.enformer_tss_embedding.zarr
    gene_intervals: /Users/nsofroniew/Documents/data/multiomics/enformer/Homo_sapiens.GRCh38.genes.bed
    pcs: 256
  cell_embeddings:
    pcs: 256
    key: train
  bulk_data:
    sample_col: dataset_id # Use donor_id or dataset_id
    label_col: cell_type
    min_cells: 50
  filter:
    coding_only: True
  split:
    seed: 42
    fraction: 0.7
    key: train
  expression_transform:
    total_counts: 100_000
    log1p: True
    n_bins: 128
  markers:
    label_col: ${preprocessing.bulk_data.label_col}
    total_counts: ${preprocessing.expression_transform.total_counts}
    log1p: ${preprocessing.expression_transform.log1p}
    mean_expression_threshold: 0.1
    score_quantile: 0.9
module:
  learning_rate: 0.001
  criterion:
    loss_function: mse
device: cuda # cuda or cpu
num_devices: 8 # 8 or 1
defaults:
  - data_module: transformer
  - module/model: transformer