hydra:
  run:
      dir: /home/ec2-user/enformer/outputs/${adata.embedding_type}/${now:%Y-%m-%d}/${now:%H-%M-%S}
paths:
  adata: /home/ec2-user/enformer/tabula_sapiens_by_features_with_embeds_new_norm.h5ad
  chkpt: null
params:
  batch_size: 128
  learning_rate: 0.001
defaults:
  - adata: gene
  - model: single