defaults:
  - data_module: masked_var
  - preprocessing: standard
  - module/optimizer: adamw
  - module/model: transformer
  - trainer: cuda

hydra:
  run:
    dir: /home/ec2-user/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} # /home/ec2-user/ or /Users/nsofroniew/Documents/data/rosa/

paths:
  base: /home/ec2-user/cell_census # /home/ec2-user/ or /Users/nsofroniew/Documents/data/multiomics/
  dataset: tabula_sapiens
  preprocessed: _5x_top10_pc__sample_${preprocessing.bulk_data.sample_col}__label_${preprocessing.bulk_data.label_col}
  chkpt: null #/home/ec2-user/outputs/2023-04-01/16-59-32/checkpoints/last.ckpt

module:
  criterion:
    loss_function: ce

