hydra:
  run:
      dir: /Users/nsofroniew/Documents/data/rosa/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
paths:
  base: /Users/nsofroniew/Documents/data/multiomics/cell_census
  dataset: tabula_sapiens
  preprocessed: _sample_${preprocessing.bulk_data.sample_col}__label_${preprocessing.bulk_data.label_col}
  chkpt: null
preprocessing:
  gene_embeddings:
    path: /Users/nsofroniew/Documents/data/multiomics/enformer/Homo_sapiens.GRCh38.genes.enformer_tss_embedding.zarr
    gene_intervals: /Users/nsofroniew/Documents/data/multiomics/enformer/Homo_sapiens.GRCh38.genes.bed
    pcs: 256
  cell_embeddings:
    pcs: 256
    key: train
  bulk_data:
    sample_col: dataset_id # Use donor_id or dataset_id
    label_col: cell_type
  filter:
    coding_only: True
  split:
    seed: 42
    fraction: 0.7
    key: train
  markers:
    differential_expression: ${paths.base}/${paths.dataset}_${paths.preprocessed}__scvi_de.csv
module:
  learning_rate: 0.001
  criterion:
    loss_function: mae
defaults:
  - data_module: cell
  - module/model: single-expression-head-only