data:
  expression_layer: null
  var_input: embedding
  obs_input: null
  expression_transform:
    total_counts: null
    log1p: null
    n_bins: 8
    zero_bin: False
  n_var_sample: null
  n_obs_sample: null
  mask: 0.2
  pass_through: 0.1
  corrupt: 0.1
batch_size: 1 # 1 or 4 or 2 ## Batch size should be ~2M tokens e.g. 100-200 samples?
accumulate: 4 # 20 or 2 or 8
num_workers: 0 # 16 or 0