data:
  expression_layer: null
  var_input: embedding
  obs_input: null
  expression_transform:
    total_counts: null
    log1p: null
    n_bins: 16
  n_var_sample: 12000
  mask: 0.15
batch_size: 4
accumulate: 2
num_workers: 16 # 8 or 0