data:
  expression_layer: null
  var_input: embedding
  obs_input: null
  expression_transform:
    total_counts: null
    log1p: null
    n_bins: 16
    zero_bin: False
  n_var_sample: 12000
  n_obs_sample: 12000
  mask: 0.2
  pass_through: 0.1
  corrupt: 0.1
batch_size: 2 # 4 or 2
accumulate: 8 # 2 or 8
num_workers: 0 # 16 or 0